---
# tasks file for grafana

# Install grafana on Ubuntu via apt
- name: install gpg for grafana - Debian
  apt:
    name: gnupg,software-properties-common
    state: present
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_os_family == "Debian"

- name: add gpg key for grafana - Debian
  apt_key:
    url: "https://packages.grafana.com/gpg.key"
    validate_certs: no
  when: ansible_os_family == "Debian"

- name: add repository for grafana - Debian
  apt_repository:
    repo: "deb https://packages.grafana.com/oss/deb stable main"             
    state: present
    validate_certs: no
  when: ansible_os_family == "Debian"

- name: install grafana - Debian
  apt:
    name: grafana
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_os_family == "Debian"


# Install grafana via YUM - RedHat/CentOS

- name: create grafana repo file for yum install - RedHat/CentOS
  template:
    src: grafana.repo.j2
    dest: /etc/yum.repos.d/grafana.repo
    mode: 0755
  when: ansible_os_family == "RedHat"

- name: Install Grafana YUM - RedHat/CentOS
  yum:
    name: grafana
    state: present
  when: ansible_os_family == "RedHat"

- name: Install fontconfig YUM  - RedHat/CentOS
  yum:
    name: fontconfig
    state: present
  when: ansible_os_family == "RedHat"

- name: Install freetype* YUM - RedHat/CentOS
  yum:
    name: freetype*
    state: present
  when: ansible_os_family == "RedHat"

- name: Install Grafana YUM - RedHat/CentOS
  yum:
    name: urw-fonts
    state: present
  when: ansible_os_family == "RedHat" 


# Start Service and Set Admin Pswd
- name: start grafana
  systemd:
    name: grafana-server
    state: started
    enabled: yes

- name: start service grafana-server
  systemd:
    name: grafana-server
    state: started
    enabled: yes

- name: wait for service up
  uri:
    url: "http://127.0.0.1:3000"
    status_code: 200
  register: __result
  until: __result.status == 200
  retries: 120
  delay: 1

- name: change admin password for grafana gui
  shell : "grafana-cli admin reset-admin-password {{ grafana_admin_password }}"
  register: __command_admin
  changed_when: __command_admin.rc !=0

