---
# tasks file for grafana

# Install grafana on Ubuntu via apt
- name: install gpg for grafana - Debian
  apt:
    name: gnupg,software-properties-common
    state: present
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_os_family == "Debian"

- name: add gpg key for grafana - Debian
  apt_key:
    url: "https://packages.grafana.com/gpg.key"
    validate_certs: no
  when: ansible_os_family == "Debian"

- name: add repository for grafana - Debian
  apt_repository:
    repo: "deb https://packages.grafana.com/oss/deb stable main"             
    state: present
    validate_certs: no
  when: ansible_os_family == "Debian"

- name: install grafana - Debian
  apt:
    name: grafana
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_os_family == "Debian"


# Install grafana via YUM - RedHat/CentOS

- name: create grafana repo file for yum install - RedHat/CentOS
  template:
    src: grafana.repo.j2
    dest: /etc/yum.repos.d/grafana.repo
    mode: 0755
  when: ansible_os_family == "RedHat"

- name: Install Grafana YUM - RedHat/CentOS
  yum:
    name: grafana
    state: present
  when: ansible_os_family == "RedHat"

- name: Install fontconfig YUM  - RedHat/CentOS
  yum:
    name: fontconfig
    state: present
  when: ansible_os_family == "RedHat"

- name: Install freetype* YUM - RedHat/CentOS
  yum:
    name: freetype*
    state: present
  when: ansible_os_family == "RedHat"

- name: Install Grafana YUM - RedHat/CentOS
  yum:
    name: urw-fonts
    state: present
  when: ansible_os_family == "RedHat" 


# Start Service and Set Admin Pswd
- name: start grafana
  systemd:
    name: grafana-server
    state: started
    enabled: yes

- name: start service grafana-server
  systemd:
    name: grafana-server
    state: started
    enabled: yes

- name: wait for service up
  uri:
    url: "http://127.0.0.1:3000"
    status_code: 200
  register: __result
  until: __result.status == 200
  retries: 120
  delay: 1

- name: change admin password for grafana gui
  shell : "grafana-cli admin reset-admin-password {{ grafana_admin_password }}"
  register: __command_admin
  changed_when: __command_admin.rc !=0

- name: set grafana datasource
  grafana_datasource:
    name: "{{ grafana_datasource_name }}"
    grafana_url: "http://127.0.0.1:3000"
    grafana_password: "{{ grafana_admin_password }}"
    ds_type: prometheus
    url: "http://127.0.0.1:9090"
    state: present


- name: download grafana dashboard 
  get_url:
    url: https://grafana.com/api/dashboards/{{ grafana_dash_id }}/revisions/{{ grafana_dash_rev }}/download
    dest: "/etc/grafana/dashboard_{{ grafana_dash_id }}_rev_{{ grafana_dash_rev }}.json"
    mode: 0644

- name: Set the correct data source name in the dashboard
  replace:
    dest: "/etc/grafana/dashboard_{{ grafana_dash_id }}_rev_{{ grafana_dash_rev }}.json"
    regexp: '"(?:\${)?DS_[A-Z0-9_-]+(?:})?"'
    replace: '"{{ grafana_datasource_name }}"'

- name: Set the dashboard as the default in grafana config file and restart grafana
  replace:
    dest: "/etc/grafana/grafana.ini"
    regexp: '(;default_home_dashboard_path =)'
    replace: 'default_home_dashboard_path = /etc/grafana/dashboard_{{ grafana_dash_id }}_rev_{{ grafana_dash_rev }}.json'
  notify: restart_grafana

#;default_home_dashboard_path = 


#- name: Import Grafana dashboard 
#  grafana_dashboard:
#    grafana_url: "http://127.0.0.1:3000"
#    grafana_password: "{{ grafana_admin_password }}"
#    state: present
#    overwrite: yes
#    path: "/etc/grafana/dashboard_{{ grafana_dash_id }}_rev_{{ grafana_dash_rev }}.json"

