---

# ----------------------------------------------
# Install grafana via apt - Debian
# ----------------------------------------------
- name: install dependencies for Grafana - apt
  apt:
    name:
      - gnupg
      - software-properties-common
    state: present
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_os_family == "Debian"

- name: add gpg key for grafana - apt
  apt_key:
    url: "https://packages.grafana.com/gpg.key"
    validate_certs: yes
  when: ansible_os_family == "Debian"

- name: add repository for grafana - apt
  apt_repository:
    repo: "deb https://packages.grafana.com/oss/deb stable main"
    state: present
    validate_certs: yes
  when: ansible_os_family == "Debian"

- name: install grafana - apt
  apt:
    name: grafana
    state: present
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_os_family == "Debian"


# ----------------------------------------------
# Install grafana via YUM - RedHat/CentOS
# ----------------------------------------------

- name: Install dependencies for Grafana - yum
  yum:
    name:
      - fontconfig
      - freetype*
      - urw-fonts
    state: present
  when: ansible_os_family == "RedHat"

- name: Create Grafana repo file - yum
  template:
    src: grafana.repo.j2
    dest: /etc/yum.repos.d/grafana.repo
    mode: 0755
  when: ansible_os_family == "RedHat"

- name: Install Grafana - yum
  yum:
    name: grafana
    state: present
  when: ansible_os_family == "RedHat"



# Set the Listen Port for Grafana server

- name: Set the listen port for the Admin Interface
  replace:
    dest: "/etc/grafana/grafana.ini"
    regexp: '[;]?(http_port = )(\d*)'
    replace: 'http_port = {{ grafana_listen_port }}'
  notify: restart_grafana


# Start Service

- name: Start service grafana-server
  systemd:
    name: grafana-server
    state: started
    enabled: yes


# Set Grafana Configuration; Admin Pswd, Data Source, and setup Dashboard

- name: wait for service up
  uri:
    url: "http://127.0.0.1:{{ grafana_listen_port }}"
    status_code: 200
  register: __result
  until: __result.status == 200
  retries: 120
  delay: 1

- name: Change admin password for Grafana GUI
  shell : "grafana-cli admin reset-admin-password {{ grafana_admin_password }}"
  register: __command_admin
  changed_when: __command_admin.rc !=0

- name: Set Grafana datasources
  grafana_datasource:
    grafana_url: "http://127.0.0.1:{{ grafana_listen_port }}"
    grafana_password: "{{ grafana_admin_password }}"
    name: "{{ item.name }}"
    ds_type: "{{ item.type }}"
    ds_url: "{{ item.url }}"
    state: present
  with_items: "{{ grafana_datasources }}"


- include: dashboards.yml
  when: grafana_dashboards | length > 0
  tags:
    - grafana_configure
    - grafana_dashboards
    - grafana_run

